import type { Metadata } from "next";
import "./globals.css";
import {Roboto} from "next/font/google"

const robotoLatin = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto-latin",
  weight: ["100", "300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Pratham Satani</title>
      </head>
      <body
        className={`${robotoLatin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
